---
# tasks file for mapr-client
# - name: install mapr-core (for conf/env.sh)
#   yum: name=mapr-core state=present

# - name: configure env.sh with JAVA_HOME
#   lineinfile: dest=/opt/mapr/conf/env.sh insertafter="^#export JAVA_HOME" state=present line="export JAVA_HOME={{java_home}}" 

- name: install mapr-client
  yum: name=mapr-client state=present
  environment: proxy_env

- name: copy ssl_truststore (secure cluster only)
  copy: src=/tmp/ssl_truststore dest=/opt/mapr/conf mode=0600 
  when: secure_cluster is defined

- name: copy maprserverticket (secure cluster only)
  copy: src=/tmp/maprserverticket dest=/opt/mapr/conf mode=0600 
  when: secure_cluster is defined

- name: see if this node is already configured
  stat: path=/opt/mapr/conf/mapr-clusters.conf
  register: mapr_clusters

- name: write configure script
  template: src=client_configure_sh.j2 dest=/tmp/client_configure.sh mode=0700 owner=root group=root 
  when: mapr_clusters.stat.exists == false

- name: configure this client
  command: /tmp/client_configure.sh chdir=/tmp
  when: mapr_clusters.stat.exists == false

- name: remove configuration script
  file: state=absent path=/tmp/client_configure.sh 
