
- name: install mapr packages
  yum: name='{{item}}' state=present
  with_items:
    - mapr-fileserver
  when: ansible_distribution == "CentOS" or ansible_distribution == "Redhat"

- name: write out disk config
  template: src=disks.txt.j2 dest=/tmp/disks.txt mode=0644 owner=root group=root

- name: configure env.sh with JAVA_HOME
  lineinfile: dest=/opt/mapr/conf/env.sh insertafter="^#export JAVA_HOME" state=present line="export JAVA_HOME={{java_home}}" 

- name: open port 8443 for the MCS
  command: iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 8443 -j ACCEPT

- name: save iptables configuration
  command: service iptables save

- name: configure single-node cluster
  command: /opt/mapr/server/configure.sh -M7 -C {{ansible_hostname}} -Z {{ansible_hostname}}  -N vagrant -a -du maprmetrics -dp mapr -d localhost:3306

- name: check whether we have disks already
  shell: /opt/mapr/server/disklist.sh
  register: disklist

- name: print the disklist
  debug: msg={{disklist.stdout.find('MapR-FS')}}

- name: add the disks
  command: /opt/mapr/server/disksetup /tmp/disks.txt
  when: disklist.stdout.find('MapR-FS') == -1

- name: set a password for the mapr user
  user: name=mapr password='$1$6rkjHhj1$VCrBrOAXCl04VfpSDYumQ/'
