---
# tasks file for sparkslave

# Assumes the MapR repos are already configured.

- name: install mapr-spark for Redhat/CenOS
  yum: name='{{item}}' state=present
  with_items:
    - mapr-spark
  when: ansible_distribution == "CentOS" or ansible_distribution == "Redhat"

- name: install mapr-spark for Debian/Ubuntu
  apt: name='{{item}}' state=present
  with_items:
    - mapr-spark
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

#- name: set spark work directory in spark configuration
#  lineinfile: 

- name: create a spark work directory
  file: dest=/opt/mapr/spark/work owner=mapr group=mapr state=directory mode=0750
