---
# tasks file for mapr-hive
# mysql_root_password comes from top-level group_vars/all

- name: install mysqldb which is required for ansible
  yum: name=MySQL-python state=present

- name: install hive $hive_version and related packages
  yum: name={{item}} state=present
  with_items:
    - mysql
    - 'mapr-hive-{{hive_version}}'
    - 'mapr-hiveserver2-{{hive_version}}'
    - 'mapr-hivemetastore-{{hive_version}}'

- name: ensure the top level hive directory is owned by mapr so logs directory can be created
  file: path=/opt/mapr/hive owner=mapr group=mapr recurse=yes

# Note that this template may rely on variables in other groups, and as a result, 
# my not always work when this playbook is run individually.
- name: write .my.cnf for root
  template: src=dot-my.cnf.j2 dest=/root/.my.cnf mode=0600 owner=root group=root

- name: ensure hivemeta exists
  mysql_db:
    name="{{hive_db}}"
    state=present
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    login_host="{{hive_metastore_host}}"
  register: db_changed

- name: create the hive metastore schema
  mysql_db:
    name="{{hive_db}}"
    state=import
    target="/opt/mapr/hive/hive-0.12/scripts/metastore/upgrade/mysql/hive-schema-0.12.0.mysql.sql"
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    login_host="{{hive_metastore_host}}"
  when: db_changed.changed

- name: create mapr user@localhost
  mysql_user:
    name={{hive_db_user}}
    host="localhost"
    password="{{hive_db_pass}}"
    check_implicit_admin=yes
    priv={{hive_db}}.*:ALL
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    login_host="{{hive_metastore_host}}"

- name: create mapr user@%
  mysql_user:
    name={{hive_db_user}}
    host="%"
    password={{hive_db_pass}}
    check_implicit_admin=yes
    priv={{hive_db}}.*:ALL
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    login_host="{{hive_metastore_host}}"

- name: copy hive-site.xml into place
  template: src=hive-site.xml.j2 dest=/opt/mapr/hive/hive-0.12/conf/hive-site.xml

