---
# tasks file for mapr-nfs

- name: install mapr-nfs packages
  yum: name={{item}} state=present
  with_items:
    - mapr-nfs

# - name: create mountpoint for loopback NFS mountpoint
#   file: path=/mapr state=directory

# For each NFS server, add a local mount. Clients (such as edge nodes) will mount via system fstab.
- name: add a warden-managed local NFS mount
  template: src=mapr_fstab.j2 dest=/opt/mapr/conf/mapr_fstab mode=0644 owner=root group=root

