---
# tasks file for mapr-rh-prereqs
- name: save the current list of installed packages
  shell: rpm -qa --queryformat '%{NAME}\t%{VERSION}\n' > /root/packages_before_mapr_install
  args:
    creates: /root/packages_before_mapr_install 
    

- name: install libselinux-python tools
  yum: name="{{item}}" state=present
  with_items:
    - libselinux-python

- name: set selinux config to permissive
  selinux: state=permissive policy=targeted

- name: selinux to permissive now
  command: setenforce permissive

- name: disable iptables
  service: name=iptables state=stopped enabled=no

- name: install fastestmirror for yum
  yum: name=yum-plugin-fastestmirror state=present

- name: write /etc/hosts with cluster node names
  template: src=hosts.j2 dest=/etc/hosts mode=0644 

- name: install repo for Redhat-based Linux
  template: src=maprtech.repo.j2 dest=/etc/yum.repos.d/maprtech.repo mode=0644 owner=root group=root

- name: install Java 1.7
  yum: name={{item}} state=present
  with_items:
    - java-1.7.0-openjdk
    - java-1.7.0-openjdk-devel

- name: install NTP
  yum: name=ntp state=present
  notify: restart ntp

- name: ensure NTP is enabled
  service: name=ntpd enabled=yes state=started

- name: install nfs-utils to get rpcbind
  yum: name=nfs-utils state=installed

- name: ensure NFS server is disabled
  service: name=nfs state=stopped enabled=no

- name: ensure rpcbind starts
  service: name=rpcbind state=started enabled=yes

- name: ensure TCP retries are set to 5
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_retries2" line="net.ipv4.tcp_retries2=5"
  notify: reload sysctl

- name: disable memory overcommit
  lineinfile: dest=/etc/sysctl.conf regexp="^vm.overcommit_memory" line="vm.overcommit_memory=0"
  notify: reload sysctl

- name: create a mapr group
  group: name=mapr gid="{{mapr_gid}}"

- name: set a password for the mapr user and ensure ssh keys exist
  user: name=mapr uid="{{mapr_uid}}" group="mapr" password="{{mapr_user_pw}}" home="{{mapr_home}}" generate_ssh_key=yes state=present createhome=yes
