- name: install MySQL 
  yum: name=mysql-server state=present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Redhat"

- name: ensure MySQL starts on boot
  service: name=mysqld enabled=yes state=started

- name: install mysql python module
  yum: name=MySQL-python state=installed
  when: ansible_distribution == "CentOS" or ansible_distribution == "Redhat"

- name: lock down root user
  mysql_user: check_implicit_admin=yes login_user=root login_password={{mysql_root_password}} name=root password={{mysql_root_password}} host={{item}}
  with_items:
    - localhost
    - \%