---
# tasks file for python-lxml
- name: install python-lxml for the xml module
  yum: name="{{item}}" state=present
  with_items:
    - gcc
    - make
    - libxslt
    - libxslt-devel
    - libxml2
    - libxml2-devel
    - python-devel
    - python-setuptools
  when: ansible_distribution in ('CentOS','RedHat','Amazon')

- name: install pip
  command: easy_install pip

- name: install lxml
  pip: name=lxml state=present
