---
# tasks file for mapr-spark

# Assumes the MapR repos are already configured.

- name: install mapr-spark for RedHat/CentOS
  yum: name='{{item}}' state=present
  with_items:
    - mapr-spark-master
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
  notify:
    - re-run configure.sh to enable spark-master

- name: install mapr-spark for Debian/Ubuntu
  apt: name='{{item}}' state=present
  with_items:
    - mapr-spark-master
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  notify:
    - re-run configure.sh to enable spark-master

- name: create slaves file
  template: src=slaves.j2 dest={{spark_home}}/conf/slaves mode=0644 owner=root group=root

- name: install spark-env.sh
  template: src=spark-env.sh.j2 dest={{spark_home}}/conf/spark-env.sh.j2 mode=0644 owner=root group=root
