
--- 
- hosts: all
  gather_facts: no
  tasks:
    - name: Stop all instances referred to by inventory file
      local_action:
        module: ec2
        region: '{{ec2_region}}'
        state: 'stopped'
        instance_ids: [ "{{instance_id}}" ]
      when: instance_id is defined
