---
- hosts: all
  sudo: yes
  roles:
    - { role: mapr-configuration,
        mapr_disks: [ '/dev/xvdf', '/dev/xvdg' ],
        java_home: '/etc/alternatives/java_sdk',
        cluster_name: '{{mapr_cluster_name}}',
        metrics_user: maprmetrics,
        metrics_password: mapr,
        metrics_host: "{{ groups['hiveserver'] | first }}" }

- include: secure_cluster.yml
  tags: 
    - configure
    - secure

- hosts: cluster
  sudo: yes
  tasks:
    - name: configure cluster nodes
      command: /tmp/do_configure.sh
      args:
        chdir: /tmp
        creates: /opt/mapr/conf/mapr-cluster.conf

    - name: get the disk list
      shell: /opt/mapr/server/disklist.sh
      register: disklist 

    - name: add the disks
      command: creates=/opt/mapr/conf/disktab /opt/mapr/server/disksetup -F /tmp/disks.txt
      when: "disklist is defined and disklist.stdout.find('MapR-FS') == -1"

- hosts: edge
  tags:
    - edge
  sudo: yes
  tasks:
    - name: configure edge node
      command: /tmp/do_configure.sh
      args:
        chdir: /tmp
        creates: /opt/mapr/conf/mapr-cluster.conf

