---
- hosts: cluster;cldb;zookeepers

- hosts: hiveserver
  roles:
    - { role: metrics-database,
        mysql_root_user: root,
        mysql_root_password: mapr,
        mysql_host: "{{ groups['hiveserver'] | first }}" }

- hosts: webserver:jobtracker
  roles:
    - mapr-metrics
