
--- 
- hosts: cluster
  gather_facts: no
  max_fail_percentage: 0
  tasks:
    - name: ensure some critical vars are set, fail early if not.
      assert:
        that:
          - mapr_cluster_name is defined
          - mapr_version is defined

- include: prerequisites.yml 

- hosts: zookeepers
  tags: 
    - install
  max_fail_percentage: 0
  roles:
    - zookeeper

- hosts: cldb
  tags: 
    - install
    - cldb
  max_fail_percentage: 0
  roles:
    - mapr-cldb

- include: install_yarn.yml

- hosts: jobtracker
  tags:
    - install
    - classic
  max_fail_percentage: 0
  roles:
    - mapr-jobtracker

- hosts: tasktracker
  tags:
    - install
    - classic
  roles:
    - mapr-tasktracker

- hosts: webserver
  tags:
    - install
  roles:
    - webserver

- hosts: nfs
  tags:
    - install
    - nfs
  roles:
    - mapr-nfs

- hosts: fileserver
  tags:
    - install
  roles:
    - mapr-fileserver

# uncomment the following line to install mysql (hive metastore and metrics)
- include: install_mysql.yml
  tags:
    - install
    - mysql

# Install mapr-metrics
- hosts: hiveserver
  tags:
    - install
    - metrics
  roles:
    - { role: metrics-database,
        mysql_root_user: root,
        mysql_root_password: mapr,
        mysql_host: "{{ groups['hiveserver'] | first }}" }


- hosts: webserver;jobtracker;resourcemanager
  tags: metrics
  roles:
    - { role: mapr-metrics,
        cluster_name: '{{mapr_cluster_name}}',
        metrics_user: maprmetrics,
        metrics_password: mapr,
        metrics_host: "{{ groups['hiveserver'] | first }}" }

# uncomment the followng line to install an edge node
- include: install_edgenode.yml tags=edge


- include: configure_cluster.yml tags=configure


- hosts: zookeepers
  tasks:
    - name: ensure mapr user owns /opt/mapr/zkdata
      file: path=/opt/mapr/zkdata owner=mapr group=mapr mode=0750 state=directory

    - name: start zookeeper on ZK nodes
      service: name=mapr-zookeeper state=started enabled=yes
      register: zk_started

    - name: wait for zookeeper to be listening
      wait_for: port=5181 delay=10 timeout=90

    - name: wait for a few more seconds to let zookeepers initialize
      pause: seconds=15
      when: zk_started.changed

    - name: get zookeeper status
      command: /sbin/service mapr-zookeeper qstatus
      register: zk_qstatus

- hosts: cldb
  tags:
    - cldb
  tasks:
    - name: start warden on CLDBs first per doc.mapr.com
      service: name=mapr-warden state=started enabled=yes
      register: cldb_started

    - name: pause for a bit and wait for CLDBs to come up
      wait_for: port=7222 delay=10 timeout=90
      ignore_errors: yes
      when: cldb_started.changed == True

    - name: let CLDBs have their election and settle
      pause: seconds=90 
      when: cldb_started.changed == True

    # can't obtain the CLDB master without a ticket
    - name: get the cldbmaster
      command: maprcli node cldbmaster
      register: cldbmaster
      when: secure_cluster is not defined

    # can't obtain the CLDB master without a ticket
    - name: check that we found a cldbmaster, or fail
      assert:
        that:
          - cldbmaster.rc == 0
      when: secure_cluster is not defined

- hosts: cluster
  tasks:
    - name: start the warden on all nodes
      service: name={{item}} state=started
      with_items:
        - mapr-warden
      register: warden_started

    - name: wait a bit before proceeding
      pause: seconds=30
      when: warden_started.changed

- hosts: cluster
  roles:
    - { role: nfs-mount, cluster_name: '{{mapr_cluster_name}}' }

# Configure all cluster nodes with public key access
# This allows passwordless SSH between cluster nodes for root and mapr users.
- include: authorized_keys.yml tags=authorized_keys

#
# Having installed and started the cluster, install optional ecosystem and client services.
# Some of the below will need to be uncommented, or be run manually.
#

# uncomment the following line to install spark (spark, shark, spark-master)
#- include: install_spark.yml

# uncomment the following line to install hbase
#- include: install_hbase.yml

# uncomment the following line to install hive
- include: install_hive.yml

# uncomment the following line to install impala
#- include: install_impala.yml

- hosts: localhost
  tasks:
    - name: remove fetched maprserverticket, ssl_keystore, and ssl_truststore
      file: path=/tmp/{{item}} state=absent
      with_items:
        - maprserverticket
        - ssl_keystore
        - ssl_truststore
        - cldb.key

- hosts: cldb[0]
#  sudo: yes
#  sudo_user: mapr
  tasks:
    - name: set default desired replication to 1
      command: maprcli config save -values "{cldb.volumes.default.replication:1}"
      when: single_node_cluster is defined and single_node_cluster == True

    - name: set default min replication to 1
      command: maprcli config save -values "{cldb.volumes.default.min.replication:1}"
      when: single_node_cluster is defined and single_node_cluster == True

    - name: set replication to 1 if single node
      shell: maprcli volume list -columns volumename | grep -v volumename | awk '{print $1}' | xargs -n1 -I'{}' maprcli volume modify -name '{}' -replication 1 -minreplication 1
      when: single_node_cluster is defined and single_node_cluster == True

# For convenience, print the URL for the MCS.
- include: print_cluster_info.yml tags=cluster_info
