---
- hosts: all
  tasks:
    - group_by: key={{ansible_virtualization_type}}
    - group_by: key={{ansible_distribution}}

- hosts: CentOS;RedHat;Amazon
  max_fail_percentage: 0
  sudo: yes
  roles:
    - { role: mapr-redhat-prereqs, mapr_user_pw: '$1$yoPLWBQ6$6fvQchDTBu3Ccs3PVURpA.' }
    - { role: mapr-redhat-prereqs, mapr_uid: 2147483632 }
    - { role: mapr-redhat-prereqs, mapr_gid: 2147483632 }
    - { role: mapr-redhat-prereqs, mapr_home: '/home/mapr' }
    - mapr-redhat-prereqs

- hosts: Ubuntu;Debian
  max_fail_percentage: 0
  sudo: yes
  roles:
    - { role: mapr-debian-prereqs, mapr_user_pw: '$1$yoPLWBQ6$6fvQchDTBu3Ccs3PVURpA.' }
    - { role: mapr-debian-prereqs, mapr_uid: 2147483632 }
    - { role: mapr-debian-prereqs, mapr_gid: 2147483632 }
    - { role: mapr-debian-prereqs, mapr_home: '/home/mapr' }
    - mapr-debian-prereqs
